'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useState} from 'react';
type Calibration={anchors:number[];width:number};
const names=['Shoulders','Waist','Wrists','Knees','Ankles'];
export function AvatarCalibration({choice,jobs,onSaved}:{choice:string;jobs:string[];onSaved:()=>void}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState<Calibration|null>(null),[defaults,setDefaults]=useState<Calibration|null>(null),[url,setUrl]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const jobKey=jobs.join(',');
 useEffect(()=>{if(!open||!choice)return;let stale=false;setDraft(null);fetch('/api/inventory/sprites?kind=avatar-settings').then(async r=>{if(!r.ok)throw Error('Could not load fitting settings');return r.json();}).then(d=>{if(!stale){setDefaults(d.default_calibration);setDraft(d.calibration||d.default_calibration);}}).catch(e=>{if(!stale)setError(e.message);});return()=>{stale=true;};},[choice,open]);
 useEffect(()=>{if(!open||!draft)return;const controller=new AbortController();let objectUrl='';const timer=setTimeout(async()=>{try{const r=await fetch('/api/inventory/sprites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'composite',jobs,previewCalibration:draft}),signal:controller.signal});if(!r.ok)throw Error('Keep landmarks ordered and at least 8 pixels apart.');objectUrl=URL.createObjectURL(await r.blob());if(controller.signal.aborted){URL.revokeObjectURL(objectUrl);return;}setUrl(objectUrl);setError('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Preview unavailable');}},200);return()=>{clearTimeout(timer);controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[open,draft,jobKey]);
 async function save(reset=false){setSaving(true);try{const r=await fetch('/api/inventory/sprites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'avatar-calibration',choice,calibration:reset?null:draft})});if(!r.ok)throw Error('Could not save fitting settings. Check the landmark order.');if(reset)setDraft(defaults);onSaved();setError('');}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setSaving(false);}}
 return <details className="ur-sprite-tools" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Fit clothes to this avatar</summary><p>Move the guides to your avatar’s joints. Adjust width to match the arms. Only the clothes move; your sprite is preserved. Settings are separate for each avatar choice.</p>{draft&&<div className="ur-calibration"><div className="ur-calibration-preview">{url&&<img src={url} alt="Preview of clothing fitted to your avatar"/>}{draft.anchors.map((y,i)=><span key={names[i]} style={{top:`${y/276*100}%`}}>{names[i]}</span>)}</div><div>{draft.anchors.map((y,i)=><label key={names[i]}>{names[i]}<input aria-label={`${names[i]} position`} type="range" min={20} max={270} value={y} onChange={e=>setDraft({...draft,anchors:draft.anchors.map((v,j)=>j===i?Number(e.target.value):v)})}/><output>{y}</output></label>)}<label>Clothing width<input aria-label="Clothing width" type="range" min={32} max={160} value={draft.width} onChange={e=>setDraft({...draft,width:Number(e.target.value)})}/><output>{draft.width}</output></label><button disabled={saving||!!error} onClick={()=>void save()}>Save fit</button><button disabled={saving} onClick={()=>void save(true)}>Reset fit</button></div></div>}{error&&<p role="alert">{error}</p>}</details>;
}
